# Docker Compose override for staging environment
version: '3.8'

services:
  backend:
    environment:
      - DEBUG=false
      - FRONTEND_URL=https://staging.diidemo.hr
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    environment:
      - VITE_API_BASE_URL=https://api-staging.diidemo.hr/api
    restart: unless-stopped

  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_STAGING}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped

  redis:
    restart: unless-stopped

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped

volumes:
  postgres_staging_data: