# Docker Compose override for production environment
version: '3.8'

services:
  backend:
    environment:
      - DEBUG=false
      - FRONTEND_URL=https://diidemo.hr
      - ENABLE_SCHEDULER=true
    volumes:
      - ./logs:/app/logs
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1GB
        reservations:
          cpus: '0.5'
          memory: 512MB

  frontend:
    environment:
      - VITE_API_BASE_URL=https://api.diidemo.hr/api
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB

  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2GB

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256MB

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: always

volumes:
  postgres_prod_data: