global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@kruznakarta.hr'
  smtp_auth_username: 'alerts@kruznakarta.hr'
  smtp_auth_password: 'alert_password'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 2h
    
    - match:
        service: database
      receiver: 'database-alerts'
    
    - match:
        service: api
      receiver: 'api-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://backend:8000/api/monitoring/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@kruznakarta.hr'
        subject: '[CRITICAL] Kruzna Karta Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
    
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          {{ end }}

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@kruznakarta.hr'
        subject: '[WARNING] Kruzna Karta Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'database-alerts'
    email_configs:
      - to: 'dba@kruznakarta.hr'
        subject: '[DATABASE] Kruzna Karta Database Alert: {{ .GroupLabels.alertname }}'
        body: |
          Database Alert Triggered:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          
          Recommended Actions:
          - Check database connection pool
          - Review slow query log
          - Monitor system resources
          {{ end }}

  - name: 'api-alerts'
    email_configs:
      - to: 'devops@kruznakarta.hr'
        subject: '[API] Kruzna Karta API Alert: {{ .GroupLabels.alertname }}'
        body: |
          API Performance Alert:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          
          Recommended Actions:
          - Check application logs
          - Review API endpoint performance
          - Monitor system resources
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service']